const bar_terraces = [
  {
    category_id: 2,
    subcategory_id: 200,
    name: 'Antic Teatre',
    photos: [
      'https://thumbs2.imgbox.com/03/11/ix44mlhU_t.jpeg',
      'https://thumbs2.imgbox.com/a6/c1/vLuDRr3z_t.jpeg',
      'https://thumbs2.imgbox.com/ac/44/y6IwCK5M_t.jpeg',
      'https://thumbs2.imgbox.com/46/53/pmQkYC5Z_t.jpeg',
      'https://thumbs2.imgbox.com/d5/80/ZHhX16Cu_t.jpeg',
    ],
    lat: 41.38725836407649,
    lng: 2.17596375392695,
    description_es:
      'Antic Teatre es un bar de terraza en Barcelona, España. El bar está ubicado en el último piso del Hotel 1898, y ofrece impresionantes vistas de la ciudad y las Ramblas. El bar es conocido por sus cócteles creativos e innovadores, que están hechos con ingredientes de alta calidad y presentados de manera única y artística. También es famoso por su extensa selección de vinos y vermuts, que se exhiben en las paredes del bar. Antic Teatre es un lugar popular tanto para locales como para turistas, y es un gran lugar para experimentar la vibrante cultura gastronómica y vinícola de Barcelona.',
    description_en:
      'Antic Teatre is a terrace bar in Barcelona, Spain. The bar is located on the top floor of Hotel 1898, and offers stunning views of the city and the Ramblas. The bar is known for its creative and innovative cocktails, which are made with high-quality ingredients and presented in a unique and artistic way. It is also famous for its extensive selection of wines and vermouths, which are displayed on the walls of the bar. Antic Teatre is a popular spot for both locals and tourists, and it is a great place to experience the vibrant gastronomic and wine culture of Barcelona.',
    trick_es: 'Ofrecen una experiencia de cata de vinos.',
    trick_en: 'They offer a wine tasting experience.',
    schedules_es: 'Abierto de martes a domingo de 12:00 p. m. a 10:00 p. m.',
    schedules_en: 'Open Tuesday to Sunday from 12:00 p.m. to 10:00 p.m.',
    address: 'Carrer de Verdaguer i Callís, 12, 08003 Barcelona, España',
    phones: '+34 933 15 10 36',
    booking_es: 'No es necesario reservar.',
    booking_en: 'No reservation required.',
    city: 'BCN',
    instagram: 'https://www.instagram.com/anticteatre/',
    avg_price: '20 euros - 30 euros',
    google_map_link: 'https://goo.gl/maps/7Z8ZQ5Q7ZzZzZzZzZ',
    official_url: 'https://www.anticteatre.com/',
    active: true,
    last_update: new Date(),
    created: new Date(),
  },
  {
    category_id: 2,
    subcategory_id: 200,
    name: 'Pissamorena',
    photos: [
      'https://thumbs2.imgbox.com/88/1b/p4FEz8RC_t.jpeg',
      'https://thumbs2.imgbox.com/aa/46/aOp1KtCI_t.jpeg',
      'https://thumbs2.imgbox.com/55/75/Bwgc7J9q_t.jpeg',
      'https://thumbs2.imgbox.com/05/8d/4LB3O0sK_t.jpeg',
      'https://thumbs2.imgbox.com/a9/de/H0RnhQQe_t.jpeg',
    ],
    lat: 41.382636081149755,
    lng: 2.1823002505538245,
    description_es:
      'Pissamorena es un bar de terraza en Barcelona, España. El bar está ubicado en el último piso del Hotel 1898, y ofrece impresionantes vistas de la ciudad y las Ramblas. El bar es conocido por sus cócteles creativos e innovadores, que están hechos con ingredientes de alta calidad y presentados de manera única y artística. También es famoso por su extensa selección de vinos y vermuts, que se exhiben en las paredes del bar. Pissamorena es un lugar popular tanto para locales como para turistas, y es un gran lugar para experimentar la vibrante cultura gastronómica y vinícola de Barcelona.',
    description_en:
      'Pissamorena is a terrace bar in Barcelona, Spain. The bar is located on the top floor of Hotel 1898, and offers stunning views of the city and the Ramblas. The bar is known for its creative and innovative cocktails, which are made with high-quality ingredients and presented in a unique and artistic way. It is also famous for its extensive selection of wines and vermouths, which are displayed on the walls of the bar. Pissamorena is a popular spot for both locals and tourists, and it is a great place to experience the vibrant gastronomic and wine culture of Barcelona.',
    trick_es: 'Ofrecen una degustación de cócteles.',
    trick_en: 'They offer a cocktail tasting experience.',
    schedules_es: 'Abierto de lunes a sábado de 12:00 p. m. a 10:00 p. m.',
    schedules_en: 'Open Monday to Saturday from 12:00 p.m. to 10:00 p.m.',
    address: 'Carrer de Ferlandina, 34, 08001 Barcelona, España',
    phones: '+34 933 02 33 58',
    booking_es: 'No es necesario reservar.',
    booking_en: 'No reservation required.',
    city: 'BCN',
    instagram: 'https://www.instagram.com/pissamorena/',
    avg_price: '20 euros - 30 euros',
    google_map_link: 'https://goo.gl/maps/7Z8ZQ5Q7ZzZzZzZzZ',
    official_url: 'https://www.pissamorena.com/',
    active: true,
    last_update: new Date(),
    created: new Date(),
  },
];

const bar_rooftops = [
  {
    category_id: 2,
    subcategory_id: 201,
    name: 'La Terraza del Claris',
    photos: [
      'https://thumbs2.imgbox.com/89/1e/fK1yG8M2_t.jpg',
      'https://thumbs2.imgbox.com/f6/9a/Bpm214FY_t.jpeg',
      'https://thumbs2.imgbox.com/79/09/COfpxuki_t.jpeg',
      'https://thumbs2.imgbox.com/e4/78/VxGl8Z4Q_t.jpg',
      'https://thumbs2.imgbox.com/63/d7/FD6KDsKb_t.jpeg',
    ],
    lat: 41.394574604757736,
    lng: 2.165218181517777,
    description_es:
      'La Terraza del Claris es un bar en la azotea en Barcelona, España. El bar está ubicado en el último piso del Hotel Claris, y ofrece impresionantes vistas de la ciudad y la Sagrada Familia. El bar es conocido por sus cócteles creativos e innovadores, que están hechos con ingredientes de alta calidad y presentados de manera única y artística. También es famoso por su extensa selección de vinos y vermuts, que se exhiben en las paredes del bar. La Terraza del Claris es un lugar popular tanto para locales como para turistas, y es un gran lugar para experimentar la vibrante cultura gastronómica y vinícola de Barcelona.',
    description_en:
      'La Terraza del Claris is a rooftop bar in Barcelona, Spain. The bar is located on the top floor of the Claris Hotel, and offers stunning views of the city and the Sagrada Familia. The bar is known for its creative and innovative cocktails, which are made with high-quality ingredients and presented in a unique and artistic way. It is also famous for its extensive selection of wines and vermouths, which are displayed on the walls of the bar. La Terraza del Claris is a popular spot for both locals and tourists, and it is a great place to experience the vibrant gastronomic and wine culture of Barcelona.',
    trick_es: 'Ofrecen una experiencia de cata de vinos.',
    trick_en: 'They offer a wine tasting experience.',
    schedules_es: 'Abierto de martes a domingo de 12:00 p. m. a 10:00 p. m.',
    schedules_en: 'Open Tuesday to Sunday from 12:00 p.m. to 10:00 p.m.',
    address: 'Carrer de Pau Claris, 150, 08009 Barcelona, España',
    phones: '+34 932 55 27 00',
    booking_es: 'No es necesario reservar.',
    booking_en: 'No reservation required.',
    city: 'BCN',
    instagram: 'https://www.instagram.com/la_terraza_del_claris/',
    avg_price: '20 euros - 30 euros',
    google_map_link: 'https://goo.gl/maps/7Z8ZQ5Q7ZzZzZzZzZ',
    official_url: 'https://www.hotelclaris.com/es/terraza-barcelona/',
    active: true,
    last_update: new Date(),
    created: new Date(),
  },
  {
    category_id: 2,
    subcategory_id: 201,
    name: 'La Isabela',
    photos: [
      'https://thumbs2.imgbox.com/04/0e/553gsRhx_t.jpeg',
      'https://thumbs2.imgbox.com/b3/1f/hIJzKioN_t.jpeg',
      'https://thumbs2.imgbox.com/09/6f/Um7MXV5v_t.jpeg',
      'https://thumbs2.imgbox.com/ee/71/PzOIF2KF_t.jpeg',
      'https://thumbs2.imgbox.com/f2/9a/e154vV8Z_t.jpeg',
    ],
    lat: 41.38367961787052,
    lng: 2.170957881517319,
    description_es:
      'La Isabela es un bar en la azotea en Barcelona, España. El bar está ubicado en el último piso del Hotel 1898, y ofrece impresionantes vistas de la ciudad y las Ramblas. El bar es conocido por sus cócteles creativos e innovadores, que están hechos con ingredientes de alta calidad y presentados de manera única y artística. También es famoso por su extensa selección de vinos y vermuts, que se exhiben en las paredes del bar. La Isabela es un lugar popular tanto para locales como para turistas, y es un gran lugar para experimentar la vibrante cultura gastronómica y vinícola de Barcelona.',
    description_en:
      'La Isabela is a rooftop bar in Barcelona, Spain. The bar is located on the top floor of the Hotel 1898, and offers stunning views of the city and the Ramblas. The bar is known for its creative and innovative cocktails, which are made with high-quality ingredients and presented in a unique and artistic way. It is also famous for its extensive selection of wines and vermouths, which are displayed on the walls of the bar. La Isabela is a popular spot for both locals and tourists, and it is a great place to experience the vibrant gastronomic and wine culture of Barcelona.',
    trick_es: 'Ofrecen una experiencia de cata de vinos.',
    trick_en: 'They offer a wine tasting experience.',
    schedules_es: 'Abierto de lunes a sábado de 12:00 p. m. a 10:00 p. m.',
    schedules_en: 'Open Monday to Saturday from 12:00 p.m. to 10:00 p.m.',
    address: 'La Rambla, 109, 08002 Barcelona, España',
    phones: '+34 933 19 12 34',
    booking_es: 'No es necesario reservar.',
    booking_en: 'No reservation required.',
    city: 'BCN',
    instagram: 'https://www.instagram.com/la_isabela_1898/',
    avg_price: '20 euros - 30 euros',
    google_map_link: 'https://goo.gl/maps/7Z8ZQ5Q7ZzZzZzZzZ',
    official_url: 'https://www.hotel1898.com/terraza-la-isabela/',
    active: true,
    last_update: new Date(),
    created: new Date(),
  },
];

const bar_speakeasy = [
  {
    category_id: 2,
    subcategory_id: 202,
    name: "Bobby's Free",
    photos: [
      'https://thumbs2.imgbox.com/e8/bd/15WD6vom_t.jpeg',
      'https://thumbs2.imgbox.com/79/3e/rkMPxmMm_t.jpeg',
      'https://thumbs2.imgbox.com/70/3f/NDvQ1L0P_t.jpeg',
      'https://thumbs2.imgbox.com/e3/d0/fdfqHoT6_t.jpeg',
      'https://thumbs2.imgbox.com/be/0b/gvof7udC_t.jpeg',
    ],
    lat: 41.39004674881424,
    lng: 2.1706792256963667,
    description_es:
      "Bobby's Free es un bar clandestino en Barcelona, España. Situado en el corazón del Barrio Gótico, este tesoro oculto ofrece una escapada a un mundo de indulgencia clandestina. Los clientes pueden disfrutar de una variedad de cócteles meticulosamente elaborados, cada uno mezclando ingredientes de alta calidad con ingenio y creatividad. El ambiente íntimo del bar y su decoración ecléctica proporcionan el escenario perfecto para disfrutar de su extensa selección de vinos y vermuts, aumentando el atractivo de la experiencia. Bobby's Free es un destino querido tanto por los lugareños como por los visitantes que buscan una experiencia inolvidable en la animada vida nocturna de Barcelona.",
    description_en:
      "Bobby's Free is a speakeasy bar in Barcelona, Spain. Located in the heart of the Gothic Quarter, this hidden gem offers an escape to a world of clandestine indulgence. Guests can enjoy a variety of meticulously crafted cocktails, each blending high-quality ingredients with wit and creativity. The intimate atmosphere of the bar and its eclectic decor provide the perfect setting to enjoy its extensive selection of wines and vermouths, enhancing the appeal of the experience. Bobby's Free is a beloved destination for both locals and visitors seeking an unforgettable experience in Barcelona's vibrant nightlife.",
    trick_es: 'Ofrecen una experiencia de cata de vinos con música en vivo.',
    trick_en: 'They offer a wine tasting experience with live music.',
    schedules_es: 'Abierto de miércoles a sábado de 8:00 p. m. a 2:00 a. m.',
    schedules_en: 'Open Wednesday to Saturday from 8:00 p.m. to 2:00 a.m.',
    address: 'Carrer de Ferran, 7, 08002 Barcelona, España',
    phones: '+34 933 17 13 63',
    booking_es: 'No es necesario reservar.',
    booking_en: 'No reservation required.',
    city: 'BCN',
    instagram: 'https://www.instagram.com/bobbysfree/',
    avg_price: '20 euros - 30 euros',
    google_map_link: 'https://goo.gl/maps/7Z8ZQ5Q7ZzZzZzZzZ',
    official_url: 'https://bobbysfree.com/',
    active: true,
    last_update: new Date(),
    created: new Date(),
  },
  {
    category_id: 2,
    subcategory_id: 202,
    name: 'Paradiso',
    photos: [
      'https://thumbs2.imgbox.com/fb/80/6EsGRiA6_t.png',
      'https://thumbs2.imgbox.com/76/0e/Oj6CyoH4_t.jpeg',
      'https://thumbs2.imgbox.com/6b/fe/jRZsl8kj_t.jpeg',
      'https://thumbs2.imgbox.com/fc/a3/Wf0Id2v1_t.jpeg',
      'https://thumbs2.imgbox.com/81/0d/Nl5pxMh8_t.jpeg',
    ],
    lat: 41.38387056716573,
    lng: 2.1837342122033485,
    description_es:
      'Paradiso es un bar clandestino en Barcelona, España. Oculto en las bulliciosas calles del Barrio Gótico, este oasis escondido ofrece una aventura sensorial como ninguna otra. Los clientes son transportados a un mundo de misterio e intriga al atravesar la entrada discreta. En su interior, descubren un reino de mixología creativa, donde los cócteles expertamente elaborados se elevan a la categoría de arte. El ambiente de Paradiso es una fusión de elegancia y fantasía, con su decoración única y entretenimiento en vivo cautivando a los visitantes en cada momento. Con su renombrada selección de vinos y vermuts, Paradiso invita a los clientes a sumergirse en la vibrante escena culinaria de Barcelona, convirtiéndose en un destino imprescindible para conocedores exigentes y aventureros curiosos por igual.',
    description_en:
      "Paradiso is a speakeasy bar in Barcelona, Spain. Hidden in the bustling streets of the Gothic Quarter, this hidden oasis offers a sensory adventure like no other. Guests are transported to a world of mystery and intrigue as they pass through the discreet entrance. Inside, they discover a realm of creative mixology, where expertly crafted cocktails are elevated to the level of art. The atmosphere of Paradiso is a fusion of elegance and fantasy, with its unique decor and live entertainment captivating visitors at every turn. With its renowned selection of wines and vermouths, Paradiso invites guests to immerse themselves in Barcelona's vibrant culinary scene, becoming a must-visit destination for discerning connoisseurs and curious adventurers alike.",
    trick_es: 'Ofrecen una experiencia de cata de cócteles con magia en vivo.',
    trick_en: 'They offer a cocktail tasting experience with live magic.',
    schedules_es: 'Abierto de martes a domingo de 7:00 p. m. a 2:30 a. m.',
    schedules_en: 'Open Tuesday to Sunday from 7:00 p.m. to 2:30 a.m.',
    address: 'Carrer de Rera Palau, 4, 08003 Barcelona, España',
    phones: '+34 933 60 72 22',
    booking_es: 'No es necesario reservar.',
    booking_en: 'No reservation required.',
    city: 'BCN',
    instagram: 'https://www.instagram.com/paradiso_barcelona/',
    avg_price: '20 euros - 30 euros',
    google_map_link: 'https://goo.gl/maps/7Z8ZQ5Q7ZzZzZzZzZ',
    official_url: 'https://paradiso.cat/',
    active: true,
    last_update: new Date(),
    created: new Date(),
  },
];

const bar_instagrammable = [
  {
    category_id: 2,
    subcategory_id: 203,
    name: 'El Nacional',
    photos: [
      'https://thumbs2.imgbox.com/16/1c/aCD5HCDC_t.jpeg',
      'https://thumbs2.imgbox.com/75/b4/ghi1PZTt_t.jpeg',
      'https://thumbs2.imgbox.com/3d/db/VEvftzXc_t.jpeg',
      'https://thumbs2.imgbox.com/cc/47/KUlmnhmi_t.jpeg',
      'https://thumbs2.imgbox.com/7e/03/ILPecJ0p_t.jpeg',
      'https://thumbs2.imgbox.com/bb/66/JJsORjzL_t.gif',
      'https://thumbs2.imgbox.com/7a/ae/RT1uFF5z_t.jpeg',
    ],
    lat: 41.39072785286495,
    lng: 2.168316295010347,
    description_es:
      'El Nacional es un bar en Barcelona, España. Situado en el corazón del Barrio Gótico, este establecimiento icónico es un destino imprescindible para los amantes de la fotografía y la cultura visual. Con su intrincada decoración y su ambiente elegante, El Nacional ofrece el telón de fondo perfecto para capturar momentos inolvidables. Los visitantes pueden disfrutar de una amplia selección de cócteles elaborados con maestría y una variedad de vinos y vermuts de alta calidad. El Nacional es más que un bar: es una experiencia visual y sensorial que cautiva a los sentidos y deja una impresión duradera.',
    description_en:
      'El Nacional is a bar in Barcelona, Spain. Located in the heart of the Gothic Quarter, this iconic establishment is a must-visit for photography enthusiasts and visual culture aficionados. With its intricate decor and elegant ambiance, El Nacional provides the perfect backdrop for capturing unforgettable moments. Visitors can enjoy a wide selection of expertly crafted cocktails and a variety of high-quality wines and vermouths. El Nacional is more than just a bar: it is a visual and sensory experience that captivates the senses and leaves a lasting impression.',
    trick_es: 'El bar cuenta con áreas temáticas para tomar fotos únicas.',
    trick_en: 'The bar features themed areas for taking unique photos.',
    schedules_es: 'Abierto todos los días de 12:00 p. m. a 2:00 a. m.',
    schedules_en: 'Open daily from 12:00 p.m. to 2:00 a.m.',
    address: 'Passeig de Gràcia, 24 Bis, 08007 Barcelona, España',
    phones: '+34 93 518 50 53',
    booking_es: 'No es necesario reservar.',
    booking_en: 'No reservation required.',
    city: 'BCN',
    instagram: 'https://www.instagram.com/elnacionalbcn/',
    avg_price: '20 euros - 30 euros',
    google_map_link: 'https://goo.gl/maps/7Z8ZQ5Q7ZzZzZzZzZ',
    official_url: 'https://www.elnacionalbcn.com/',
    active: true,
    last_update: new Date(),
    created: new Date(),
  },
  {
    category_id: 2,
    subcategory_id: 203,
    name: 'Dry Martini',
    photos: [
      'https://thumbs2.imgbox.com/91/f8/V2yCXG9G_t.jpeg',
      'https://thumbs2.imgbox.com/72/de/dWhVnwUp_t.jpeg',
      'https://thumbs2.imgbox.com/17/ba/kWEnL4ua_t.jpeg',
      'https://thumbs2.imgbox.com/68/ae/dJDaPzfq_t.jpeg',
      'https://thumbs2.imgbox.com/7a/91/sC5PUeTE_t.jpeg',
    ],
    lat: 41.39285705581174,
    lng: 2.154025668025001,
    description_es:
      'Dry Martini es un bar en Barcelona, España. Ubicado en el corazón del Barrio Gótico, este refugio elegante es conocido por su encanto clásico y su ambiente atemporal. Con su estética sofisticada y su servicio impecable, Dry Martini es un paraíso para los amantes de la fotografía en busca de la foto perfecta. Los clientes pueden disfrutar de una amplia gama de cócteles clásicos y contemporáneos, así como de una selección de vinos y vermuts de primera calidad. Con su ambiente íntimo y su decoración exquisita, Dry Martini ofrece una experiencia fotográfica inigualable en el corazón de Barcelona.',
    description_en:
      'Dry Martini is a bar in Barcelona, Spain. Located in the heart of the Gothic Quarter, this elegant refuge is known for its classic charm and timeless ambiance. With its sophisticated aesthetic and impeccable service, Dry Martini is a paradise for photography enthusiasts in search of the perfect shot. Guests can enjoy a wide range of classic and contemporary cocktails, as well as a selection of top-quality wines and vermouths. With its intimate atmosphere and exquisite decor, Dry Martini offers an unparalleled photographic experience in the heart of Barcelona.',
    trick_es:
      'El bar ofrece un menú especial para fotos con iluminación ideal.',
    trick_en: 'The bar offers a special menu for photos with ideal lighting.',
    schedules_es: 'Abierto todos los días de 6:00 p. m. a 2:30 a. m.',
    schedules_en: 'Open daily from 6:00 p.m. to 2:30 a.m.',
    address: 'Carrer d’Aribau, 162-166, 08036 Barcelona, España',
    phones: '+34 932 17 50 75',
    booking_es: 'No es necesario reservar.',
    booking_en: 'No reservation required.',
    city: 'BCN',
    instagram: 'https://www.instagram.com/drymartinibcn/',
    avg_price: '20 euros - 30 euros',
    google_map_link: 'https://goo.gl/maps/7Z8ZQ5Q7ZzZzZzZzZ',
    official_url: 'https://www.drymartiniorg.com/',
    active: true,
    last_update: new Date(),
    created: new Date(),
  },
];

const bars_subcategories = [
  {
    id: '200',
    name: 'Terraces',
    category_id: '2',
    t_name: 'subcat_terraces',
    icon: 'terraces.svg',
  },
  {
    id: '201',
    category_id: '2',
    name: 'Rooftops',
    t_name: 'subcat_rooftops',
    icon: 'rooftops.svg',
  },
  {
    id: '202',
    category_id: '2',
    name: 'Speakeasy',
    t_name: 'subcat_speakeasy',
    icon: 'speakeasy.svg',
  },
  {
    id: '203',
    category_id: '2',
    name: 'Instagrameable',
    t_name: 'subcat_instagrammable',
    icon: 'instagrammable.svg',
  },
];

const bars_places = [
  ...bar_terraces,
  ...bar_rooftops,
  ...bar_speakeasy,
  ...bar_instagrammable,
];

module.exports = { bars_subcategories, bars_places };
