const entertainment_nightlife = [
  {
    category_id: 3,
    subcategory_id: 300,
    name: 'Pacha',
    photos: [
      'https://thumbs2.imgbox.com/9b/8b/w3X3PXGs_t.jpeg',
      'https://thumbs2.imgbox.com/8c/06/z8A5tELq_t.jpeg',
      'https://thumbs2.imgbox.com/ef/68/7kUiLdfL_t.jpeg',
      'https://thumbs2.imgbox.com/93/48/UNQqKfyE_t.jpeg',
      'https://thumbs2.imgbox.com/4d/71/m4JGTIM4_t.jpeg',
    ],
    lat: 41.38592118791483,
    lng: 2.1970742087188073,
    description_es:
      'Pacha es una discoteca en Barcelona, España. Situada en el corazón del Barrio Gótico, esta icónica discoteca es conocida por su atmósfera vibrante y enérgica. Pacha también es famosa por su amplia selección de música, que incluye house, techno y hip-hop. Es un lugar popular tanto para los locales como para los turistas, y es un excelente lugar para experimentar la animada vida nocturna de Barcelona.',
    description_en:
      "Pacha is a nightclub in Barcelona, Spain. Located in the heart of the Gothic Quarter, this iconic nightclub is known for its vibrant and energetic atmosphere. Pacha is also famous for its wide selection of music, including house, techno, and hip-hop. It is a popular spot for both locals and tourists, and is a great place to experience Barcelona's lively nightlife.",
    trick_es: 'Ofrecen descuentos especiales para grupos grandes.',
    trick_en: 'They offer special discounts for large groups.',
    schedules_es: 'Abierto de jueves a domingo de 11:00 p. m. a 6:00 a. m.',
    schedules_en: 'Open Thursday to Sunday from 11:00 p.m. to 6:00 a.m.',
    address: 'Passeig Marítim de la Barceloneta, 38, 08003 Barcelona, España',
    phones: '+34 932 25 15 97',
    booking_es: 'No es necesario reservar.',
    booking_en: 'No reservation required.',
    city: 'BCN',
    instagram: 'https://www.instagram.com/pachabarcelona/',
    avg_price: '20 euros - 30 euros',
    google_map_link: 'https://goo.gl/maps/7Q7ZQ5Q7',
    official_url: 'https://pachabarcelona.es/',
    active: true,
    last_update: new Date(),
    created: new Date(),
  },
  {
    category_id: 3,
    subcategory_id: 300,
    name: 'Sala Apolo',
    photos: [
      'https://thumbs2.imgbox.com/e3/42/u9W0Wy8V_t.jpeg',
      'https://thumbs2.imgbox.com/b1/c1/R6VIxtgM_t.jpeg',
      'https://thumbs2.imgbox.com/66/c1/rZntDLEQ_t.jpeg',
      'https://thumbs2.imgbox.com/e5/04/xIjI9mG0_t.jpeg',
      'https://thumbs2.imgbox.com/e8/5c/yFXFOgcz_t.jpeg',
    ],
    lat: 41.37454303597069,
    lng: 2.169650312202976,
    description_es:
      'Sala Apolo es una discoteca en Barcelona, España. Situada en el corazón del Barrio Gótico, esta famosa discoteca es conocida por su atmósfera vibrante y enérgica. Sala Apolo también es famosa por su amplia selección de música, que incluye house, techno y hip-hop. Es un lugar popular tanto para los locales como para los turistas, y es un excelente lugar para experimentar la animada vida nocturna de Barcelona.',
    description_en:
      "Sala Apolo is a nightclub in Barcelona, Spain. Located in the heart of the Gothic Quarter, this famous nightclub is known for its vibrant and energetic atmosphere. Sala Apolo is also famous for its wide selection of music, including house, techno, and hip-hop. It is a popular spot for both locals and tourists, and is a great place to experience Barcelona's lively nightlife.",
    trick_es: 'Organizan eventos temáticos mensuales.',
    trick_en: 'They organize monthly themed events.',
    schedules_es: 'Abierto de miércoles a domingo de 11:00 p. m. a 6:00 a. m.',
    schedules_en: 'Open Wednesday to Sunday from 11:00 p.m. to 6:00 a.m.',
    address: 'Carrer Nou de la Rambla, 113, 08004 Barcelona, España',
    phones: '+34 934 41 40 01',
    booking_es: 'No es necesario reservar.',
    booking_en: 'No reservation required.',
    city: 'BCN',
    instagram: 'https://www.instagram.com/sala_apolo/',
    avg_price: '20 euros - 30 euros',
    google_map_link: 'https://goo.gl/maps/7Q7ZQ5Q7',
    official_url: 'https://www.sala-apolo.com/',
    active: true,
    last_update: new Date(),
    created: new Date(),
  },
];

const entertainment_rumba_and_flamenco = [
  {
    category_id: 3,
    subcategory_id: 301,
    name: 'Tablao Cordobes',
    photos: [
      'https://thumbs2.imgbox.com/53/d3/vmVA2mZo_t.jpeg',
      'https://thumbs2.imgbox.com/0f/09/g5Q6jv2M_t.jpeg',
      'https://thumbs2.imgbox.com/b8/ca/59R5Wuy8_t.jpeg',
      'https://thumbs2.imgbox.com/0f/7c/8ca3ErEO_t.jpeg',
      'https://thumbs2.imgbox.com/47/3a/BURV5gkn_t.jpg',
      'https://thumbs2.imgbox.com/0a/61/r37ogqPk_t.jpeg',
    ],
    lat: 41.37915477699387,
    lng: 2.174897598710445,
    description_es:
      'Tablao Cordobes es un lugar emblemático en Barcelona, España, que ofrece espectáculos de rumba y flamenco. Situado en el corazón del Barrio Gótico, este tablao es conocido por su ambiente vibrante y auténtico. Los visitantes pueden disfrutar de actuaciones en vivo de artistas talentosos mientras saborean deliciosas tapas y bebidas. Tablao Cordobes es un lugar imprescindible para aquellos que deseen experimentar la pasión y la emoción del flamenco en Barcelona.',
    description_en:
      'Tablao Cordobes is an iconic venue in Barcelona, Spain, offering flamenco and rumba shows. Located in the heart of the Gothic Quarter, this tablao is known for its vibrant and authentic atmosphere. Visitors can enjoy live performances by talented artists while savoring delicious tapas and drinks. Tablao Cordobes is a must-visit for those looking to experience the passion and excitement of flamenco in Barcelona.',
    trick_es: 'Ofrecen clases de baile flamenco para principiantes.',
    trick_en: 'They offer flamenco dance classes for beginners.',
    schedules_es: 'Espectáculos todos los días de 7:00 p. m. a 1:00 a. m.',
    schedules_en: 'Shows every day from 7:00 p.m. to 1:00 a.m.',
    address: 'La Rambla, 35, 08002 Barcelona, España',
    phones: '+34 932 68 30 82',
    booking_es: 'No es necesario reservar.',
    booking_en: 'No reservation required.',
    city: 'BCN',
    instagram: 'https://www.instagram.com/tablao_cordobes/',
    avg_price: '20 euros - 30 euros',
    google_map_link: 'https://goo.gl/maps/7Q7ZQ5Q7',
    official_url: 'https://tablao.com/',
    active: true,
    last_update: new Date(),
    created: new Date(),
  },
  {
    category_id: 3,
    subcategory_id: 301,
    name: 'Quillo Bar',
    photos: [
      'https://thumbs2.imgbox.com/0d/74/Er8xanOF_t.jpeg',
      'https://thumbs2.imgbox.com/e3/ee/AZJ9yM9i_t.jpeg',
      'https://thumbs2.imgbox.com/a8/93/ynzuIqJP_t.jpeg',
      'https://thumbs2.imgbox.com/fa/b7/cRFsvDZd_t.jpeg',
      'https://thumbs2.imgbox.com/93/14/acFSzPdp_t.jpeg',
    ],
    lat: 41.389335096756355,
    lng: 2.1795897815175507,
    description_es:
      'Quillo Bar es un lugar único en Barcelona, España, que combina la rumba y el flamenco con una atmósfera acogedora y animada. Ubicado en el corazón del Barrio Gótico, este bar es conocido por su ambiente festivo y sus actuaciones en vivo de artistas locales. Los clientes pueden disfrutar de la música en directo mientras degustan auténticas tapas y cócteles. Quillo Bar es el lugar perfecto para sumergirse en la cultura española y disfrutar de una noche inolvidable en Barcelona.',
    description_en:
      'Quillo Bar is a unique venue in Barcelona, Spain, combining rumba and flamenco with a cozy and lively atmosphere. Located in the heart of the Gothic Quarter, this bar is known for its festive atmosphere and live performances by local artists. Guests can enjoy live music while indulging in authentic tapas and cocktails. Quillo Bar is the perfect place to immerse yourself in Spanish culture and enjoy an unforgettable night in Barcelona.',
    trick_es:
      'Organizan espectáculos de flamenco en vivo los viernes y sábados.',
    trick_en: 'They organize live flamenco shows on Fridays and Saturdays.',
    schedules_es: 'Abierto todos los días de 6:00 p. m. a 2:00 a. m.',
    schedules_en: 'Open every day from 6:00 p.m. to 2:00 a.m.',
    address:
      'Carrer de l`Arc de Sant Ramon del Call, 11, 08002 Barcelona, España',
    phones: '+34 933 02 40 93',
    booking_es: 'No es necesario reservar.',
    booking_en: 'No reservation required.',
    city: 'BCN',
    instagram: 'https://www.instagram.com/quillobar/',
    avg_price: '20 euros - 30 euros',
    google_map_link: 'https://goo.gl/maps/7Q7ZQ5Q7',
    official_url: 'https://www.quillobar.com/',
    active: true,
    last_update: new Date(),
    created: new Date(),
  },
];

const entertainment_tourist_attractions = [
  {
    category_id: 3,
    subcategory_id: 302,
    name: 'Park Guell',
    photos: [
      'https://thumbs2.imgbox.com/53/c5/GdqnKBs8_t.jpeg',
      'https://thumbs2.imgbox.com/11/5c/lJCMXRDA_t.jpeg',
      'https://thumbs2.imgbox.com/ad/44/Prhct682_t.jpeg',
      'https://thumbs2.imgbox.com/cd/ad/HglKU9rz_t.jpeg',
      'https://thumbs2.imgbox.com/a3/5e/BOlVNEjL_t.jpeg',
    ],
    lat: 41.41476431252395,
    lng: 2.152630123847122,
    description_es:
      'Park Guell es una atracción turística icónica en Barcelona, España. Diseñado por el renombrado arquitecto Antoni Gaudí, este parque ofrece una experiencia única en un entorno pintoresco. Situado en el corazón del Barrio Gótico, Park Guell es conocido por su arquitectura distintiva, sus coloridos mosaicos y sus impresionantes vistas de la ciudad. Los visitantes pueden pasear por los jardines, admirar las obras de arte de Gaudí y disfrutar de momentos de tranquilidad en este oasis urbano.',
    description_en:
      "Park Guell is an iconic tourist attraction in Barcelona, Spain. Designed by the renowned architect Antoni Gaudí, this park offers a unique experience in a picturesque setting. Located in the heart of the Gothic Quarter, Park Guell is known for its distinctive architecture, colorful mosaics, and stunning views of the city. Visitors can stroll through the gardens, admire Gaudí's artworks, and enjoy moments of tranquility in this urban oasis.",
    trick_es: 'Visita temprano en la mañana para evitar las multitudes.',
    trick_en: 'Visit early in the morning to avoid crowds.',
    schedules_es: 'Abierto todos los días de 8:00 a. m. a 9:30 p. m.',
    schedules_en: 'Open every day from 8:00 a.m. to 9:30 p.m.',
    address: "Carrer d'Olot, s/n, 08024 Barcelona, España",
    phones: '+34 934 09 18 31',
    booking_es: 'No es necesario reservar.',
    booking_en: 'No reservation required.',
    city: 'BCN',
    instagram: 'https://www.instagram.com/parkguell/',
    avg_price: '20 euros - 30 euros',
    google_map_link: 'https://goo.gl/maps/7Q7ZQ5Q7',
    official_url: 'https://parkguell.barcelona/',
    active: true,
    last_update: new Date(),
    created: new Date(),
  },
  {
    category_id: 3,
    subcategory_id: 302,
    name: 'Sagrada Familia',
    photos: [
      'https://thumbs2.imgbox.com/39/04/D6kQcUgF_t.jpeg',
      'https://thumbs2.imgbox.com/2b/05/eyoSjQiL_t.jpeg',
      'https://thumbs2.imgbox.com/e3/cb/gLqoqkLv_t.jpeg',
      'https://thumbs2.imgbox.com/f7/35/bUr5a8cd_t.jpeg',
      'https://thumbs2.imgbox.com/bb/58/QD06udgs_t.jpeg',
    ],
    lat: 41.40383897935739,
    lng: 2.174234119286764,
    description_es:
      'La Sagrada Familia es una atracción turística emblemática en Barcelona, España. Diseñada por el arquitecto visionario Antoni Gaudí, esta basílica inacabada es una obra maestra de la arquitectura modernista. Situada en el corazón del Barrio Gótico, la Sagrada Familia es conocida por su impresionante fachada, sus intrincados detalles y su majestuosa estructura. Los visitantes pueden admirar la belleza y la grandeza de esta obra arquitectónica única mientras exploran su interior y aprenden sobre su fascinante historia.',
    description_en:
      'La Sagrada Familia is an iconic tourist attraction in Barcelona, Spain. Designed by the visionary architect Antoni Gaudí, this unfinished basilica is a masterpiece of modernist architecture. Located in the heart of the Gothic Quarter, La Sagrada Familia is known for its impressive facade, intricate details, and majestic structure. Visitors can admire the beauty and grandeur of this unique architectural work while exploring its interior and learning about its fascinating history.',
    trick_es: 'Compra tus boletos en línea para evitar largas filas.',
    trick_en: 'Purchase your tickets online to avoid long lines.',
    schedules_es: 'Abierto todos los días de 9:00 a. m. a 7:00 p. m.',
    schedules_en: 'Open every day from 9:00 a.m. to 7:00 p.m.',
    address: 'Carrer de Mallorca, 401, 08013 Barcelona, España',
    phones: '+34 932 08 04 14',
    booking_es: 'No es necesario reservar.',
    booking_en: 'No reservation required.',
    city: 'BCN',
    instagram: 'https://www.instagram.com/sagradafamiliabarcelona/',
    avg_price: '20 euros - 30 euros',
    google_map_link: 'https://goo.gl/maps/7Q7ZQ5Q7',
    official_url: 'https://sagradafamilia.org/',
    active: true,
    last_update: new Date(),
    created: new Date(),
  },
];

const entertainment_beachs = [
  {
    category_id: 3,
    subcategory_id: 303,
    name: 'Barceloneta Beach',
    photos: [
      'https://thumbs2.imgbox.com/3d/3a/Zzq5N4zE_t.jpeg',
      'https://thumbs2.imgbox.com/32/e2/Eh45h5Qj_t.jpeg',
      'https://thumbs2.imgbox.com/78/26/XmXbiaPQ_t.jpeg',
      'https://thumbs2.imgbox.com/94/05/3zLEpGym_t.jpeg',
      'https://thumbs2.imgbox.com/f0/fe/c9Cbhu1Z_t.jpeg',
    ],
    lat: 41.37848721602034,
    lng: 2.1924728536764237,
    description_es:
      'Barceloneta Beach es una de las playas más famosas de Barcelona, España. Situada junto al Barrio Gótico, esta playa es conocida por su ambiente animado y su amplia oferta de entretenimiento. Los visitantes pueden relajarse en la arena, nadar en las aguas cristalinas del mar Mediterráneo y disfrutar de actividades como voleibol playa y surf. Barceloneta Beach también cuenta con una gran variedad de bares y restaurantes que ofrecen deliciosos platos mediterráneos. Es el lugar perfecto para disfrutar del sol y el mar en Barcelona.',
    description_en:
      'Barceloneta Beach is one of the most famous beaches in Barcelona, Spain. Located next to the Gothic Quarter, this beach is known for its lively atmosphere and wide range of entertainment. Visitors can relax on the sand, swim in the crystal-clear waters of the Mediterranean Sea, and enjoy activities such as beach volleyball and surfing. Barceloneta Beach also offers a great variety of bars and restaurants serving delicious Mediterranean dishes. It is the perfect place to enjoy the sun and the sea in Barcelona.',
    trick_es: '',
    trick_en: '',
    schedules_es: '',
    schedules_en: '',
    address: '',
    phones: '',
    booking_es: '',
    booking_en: '',
    city: 'BCN',
    instagram: '',
    avg_price: '',
    google_map_link: 'https://goo.gl/maps/7Q7ZQ5Q7',
    official_url: '',
    active: true,
    last_update: new Date(),
    created: new Date(),
  },
  {
    category_id: 3,
    subcategory_id: 303,
    name: 'Nova Icaria Beach',
    photos: [
      'https://thumbs2.imgbox.com/7b/cf/NJwXHrro_t.jpeg',
      'https://thumbs2.imgbox.com/a6/e0/cs1st7N5_t.jpeg',
      'https://thumbs2.imgbox.com/9b/9e/vTrPYnzC_t.jpeg',
      'https://thumbs2.imgbox.com/40/b6/TWDSQpuT_t.jpeg',
      'https://thumbs2.imgbox.com/0b/89/WAFoEbCc_t.jpeg',
      'https://thumbs2.imgbox.com/98/e1/ngZpey47_t.jpeg',
    ],
    lat: 41.39063716730076,
    lng: 2.2022900928788247,
    description_es:
      'Nova Icaria Beach es una playa popular situada en Barcelona, España. Con su suave arena dorada y aguas tranquilas, esta playa es ideal para familias y amantes de los deportes acuáticos. Los visitantes pueden alquilar tumbonas y sombrillas, participar en juegos de playa o simplemente relajarse bajo el cálido sol mediterráneo. Nova Icaria Beach también cuenta con una gran variedad de restaurantes y chiringuitos donde se pueden degustar platos locales y cócteles refrescantes. Es un destino perfecto para disfrutar de un día de diversión y relax junto al mar.',
    description_en:
      'Nova Icaria Beach is a popular beach located in Barcelona, Spain. With its soft golden sand and calm waters, this beach is ideal for families and water sports enthusiasts. Visitors can rent sun loungers and umbrellas, take part in beach games, or simply relax under the warm Mediterranean sun. Nova Icaria Beach also offers a wide variety of restaurants and beach bars where you can taste local dishes and refreshing cocktails. It is a perfect destination to enjoy a day of fun and relaxation by the sea.',
    trick_es: '',
    trick_en: '',
    schedules_es: '',
    schedules_en: '',
    address: '',
    phones: '',
    booking_es: '',
    booking_en: '',
    city: 'BCN',
    instagram: '',
    avg_price: '',
    google_map_link: 'https://goo.gl/maps/7Q7ZQ5Q7',
    official_url: '',
    active: true,
    last_update: new Date(),
    created: new Date(),
  },
];

const entertainment_subcategories = [
  {
    id: '300',
    category_id: '3',
    name: 'Nightlife',
    t_name: 'subcat_nightlife',
    icon: 'nightlife.svg',
  },
  {
    id: '301',
    category_id: '3',
    name: 'Rumba & Flamenco',
    t_name: 'subcat_rumba_and_flamenco',
    icon: 'rumba_and_flamenco.svg',
  },
  {
    id: '302',
    category_id: '3',
    name: 'Tourist Attractions',
    t_name: 'subcat_tourist_attractions',
    icon: 'tourist_attractions.svg',
  },
  {
    id: '303',
    category_id: '3',
    name: 'Beachs',
    t_name: 'subcat_beachs',
    icon: 'beachs.svg',
  },
];

const entertainment_places = [
  ...entertainment_nightlife,
  ...entertainment_rumba_and_flamenco,
  ...entertainment_tourist_attractions,
  ...entertainment_beachs,
];

module.exports = { entertainment_subcategories, entertainment_places };
