const food_tapas = [
  {
    category_id: 1,
    subcategory_id: 100,
    name: 'Jai-Ca',
    photos: [
      'https://thumbs2.imgbox.com/b1/67/pbQVvz1L_t.jpeg',
      'https://thumbs2.imgbox.com/c4/0b/nJ7csmLr_t.jpeg',
      'https://thumbs2.imgbox.com/f5/ba/V0YReV9v_t.jpeg',
      'https://thumbs2.imgbox.com/94/13/Vrw9wQEL_t.jpeg',
      'https://thumbs2.imgbox.com/99/d1/vOHmu7oI_t.jpeg',
      'https://thumbs2.imgbox.com/43/d3/Tm2FS6EJ_t.jpeg',
    ],
    lat: 41.38175581816949,
    lng: 2.188232475830281,
    description_es:
      'Jai-Ca es un bar de tapas en Barcelona, España. Es un bar pequeño y familiar que lleva más de 60 años sirviendo tapas tradicionales. El bar es conocido por sus tapas de mariscos, que incluyen pescado frito, sardinas a la parrilla y pulpo. También es famoso por sus patatas bravas, una tapa clásica española hecha con patatas fritas y una salsa de tomate picante. Jai-Ca es un lugar popular tanto para locales como para turistas, y es un gran lugar para experimentar la comida y el ambiente tradicional de Barcelona.',
    description_en:
      'Jai-Ca is a tapas bar in Barcelona, Spain. It is a small, family-owned bar that has been serving traditional tapas for over 60 years. The bar is known for its seafood tapas, which include fried fish, grilled sardines, and octopus. It is also famous for its patatas bravas, a classic Spanish tapa made with fried potatoes and a spicy tomato sauce. Jai-Ca is a popular spot for both locals and tourists, and it is a great place to experience the traditional food and atmosphere of Barcelona.',
    trick_es: 'Ofrecen tapas gratis con cada bebida.',
    trick_en: 'They offer free tapas with every drink.',
    schedules_es: 'Abierto de lunes a domingo de 12:00 p. m. a 11:00 p. m.',
    schedules_en: 'Open Monday to Sunday from 12:00 p.m. to 11:00 p.m.',
    address: 'Carrer de Ginebra, 13, 08003 Barcelona, España',
    phones: '+34 933 19 24 56',
    booking_es: 'No es necesario reservar.',
    booking_en: 'No reservation required.',
    city: 'BCN',
    instagram: 'https://www.instagram.com/jaica_barcelona/',
    avg_price: '20 euros - 30 euros',
    google_map_link: 'https://goo.gl/maps/7Z8ZQ5Q7ZQ7ZQ5Q7ZQ',
    official_url: 'https://www.jai-ca.es/',
    active: true,
    last_update: new Date(),
    created: new Date(),
  },
  {
    category_id: 1,
    subcategory_id: 100,
    name: 'Quimet & Quimet',
    photos: [
      'https://thumbs2.imgbox.com/d3/84/WAi7IBbQ_t.jpeg',
      'https://thumbs2.imgbox.com/89/6d/uGMKS2u8_t.jpeg',
      'https://thumbs2.imgbox.com/61/32/oA3HrTWy_t.jpeg',
      'https://thumbs2.imgbox.com/70/fb/MdFettyu_t.png',
      'https://thumbs2.imgbox.com/d1/b4/ciyPSmwN_t.png',
    ],
    lat: 41.37414434710517,
    lng: 2.1655088950096864,
    description_es:
      'Quimet & Quimet es un bar de tapas de propiedad familiar en Barcelona, España. El bar es conocido por sus tapas creativas e innovadoras, que están hechas con ingredientes de alta calidad y presentadas de manera única y artística. También es famoso por su extensa selección de vinos y vermuts, que se exhiben en las paredes del bar. Quimet & Quimet es un lugar popular tanto para locales como para turistas, y es un gran lugar para experimentar la vibrante cultura gastronómica y vinícola de Barcelona.',
    description_en:
      'Quimet & Quimet is a family-owned tapas bar in Barcelona, Spain. The bar is known for its creative and innovative tapas, which are made with high-quality ingredients and presented in a unique and artistic way. It is also famous for its extensive selection of wines and vermouths, which are displayed on the walls of the bar. Quimet & Quimet is a popular spot for both locals and tourists, and it is a great place to experience the vibrant gastronomic and wine culture of Barcelona.',
    trick_es: 'Ofrecen una degustación de vinos.',
    trick_en: 'They offer a wine tasting experience.',
    schedules_es: 'Abierto de martes a sábado de 12:00 p. m. a 10:00 p. m.',
    schedules_en: 'Open Tuesday to Saturday from 12:00 p.m. to 10:00 p.m.',
    address: 'Carrer del Poeta Cabanyes, 25, 08004 Barcelona, España',
    phones: '+34 934 42 31 42',
    booking_es: 'No es necesario reservar.',
    booking_en: 'No reservation required.',
    city: 'BCN',
    instagram: 'https://www.instagram.com/quimet_i_quimet/',
    avg_price: '20 euros - 30 euros',
    google_map_link: 'https://goo.gl/maps/7Z8ZQ5Q7ZQ7ZQ5Q7ZQ',
    official_url: 'https://www.quimetquimet.com/',
    active: true,
    last_update: new Date(),
    created: new Date(),
  },
];

const food_catalan = [
  {
    category_id: 1,
    subcategory_id: 102,
    name: 'Kata',
    photos: [
      'https://thumbs2.imgbox.com/4c/8b/Myhd77c3_t.jpeg',
      'https://thumbs2.imgbox.com/67/22/GEcvSHXJ_t.jpeg',
      'https://thumbs2.imgbox.com/ff/bc/f1Bp1V2G_t.jpeg',
      'https://thumbs2.imgbox.com/c9/d9/uK9286nD_t.jpeg',
      'https://thumbs2.imgbox.com/40/4d/nZL513y2_t.jpeg',
    ],
    lat: 41.4070329862245,
    lng: 2.207819854532809,
    description_es:
      'Kata es un buffet popular en Barcelona, España, conocido por su deliciosa comida y su ambiente acogedor. Situado en el corazón del Barrio Gótico, este buffet ofrece una amplia variedad de platos internacionales, desde sushi fresco hasta cocina mediterránea. Los comensales pueden disfrutar de una experiencia gastronómica única mientras se relajan con música ambiental y disfrutan de la compañía de amigos y familiares. Kata es el lugar perfecto para disfrutar de una comida abundante y satisfactoria en Barcelona.',
    description_en:
      'Kata is a popular buffet in Barcelona, Spain, known for its delicious food and cozy atmosphere. Located in the heart of the Gothic Quarter, this buffet offers a wide variety of international dishes, from fresh sushi to Mediterranean cuisine. Diners can enjoy a unique dining experience while relaxing with ambient music and enjoying the company of friends and family. Kata is the perfect place to enjoy a hearty and satisfying meal in Barcelona.',
    trick_es: 'Prueba el sushi de salmón, es su especialidad.',
    trick_en: "Try the salmon sushi, it's their specialty.",
    schedules_es: 'Abierto todos los días de 12:00 p. m. a 10:00 p. m.',
    schedules_en: 'Open every day from 12:00 p.m. to 10:00 p.m.',
    address: 'Carrer de la Llibreteria, 9, 08002 Barcelona, España',
    phones: '+34 933 10 29 28',
    booking_es: 'No es necesario reservar.',
    booking_en: 'No reservation required.',
    city: 'BCN',
    instagram: 'https://www.instagram.com/kata_barcelona/',
    avg_price: '20 euros - 30 euros',
    google_map_link: 'https://goo.gl/maps/7Z8ZQ5Q7ZQ7ZQ5Q7ZQ',
    official_url: 'https://www.katabarcelona.com/',
    active: true,
    last_update: new Date(),
    created: new Date(),
  },
  {
    category_id: 1,
    subcategory_id: 102,
    name: 'Tou Kichi Rou',
    photos: [
      'https://thumbs2.imgbox.com/3e/dd/i5MXC6uC_t.jpeg',
      'https://thumbs2.imgbox.com/93/c8/Gh8y6N10_t.jpeg',
      'https://thumbs2.imgbox.com/4b/ea/V2ujWm5U_t.jpeg',
      'https://thumbs2.imgbox.com/25/72/UbT8HqzC_t.jpeg',
      'https://thumbs2.imgbox.com/d0/b3/bO8WvbhI_t.jpeg',
    ],
    lat: 41.392089249830754,
    lng: 2.1430555968606804,
    description_es:
      'Tou Kichi Rou es un buffet único en Barcelona, España, que ofrece una auténtica experiencia gastronómica japonesa. Ubicado en el corazón del Barrio Gótico, este buffet sirve una amplia selección de platos tradicionales japoneses, como sushi, sashimi y tempura. Los clientes pueden disfrutar de una comida fresca y saludable mientras observan a los chefs expertos preparar los platos en vivo. Tou Kichi Rou es el destino ideal para los amantes de la cocina japonesa que desean probar auténticos sabores en Barcelona.',
    description_en:
      'Tou Kichi Rou is a unique buffet in Barcelona, Spain, offering an authentic Japanese dining experience. Located in the heart of the Gothic Quarter, this buffet serves a wide selection of traditional Japanese dishes, such as sushi, sashimi, and tempura. Customers can enjoy fresh and healthy food while watching expert chefs prepare dishes live. Tou Kichi Rou is the ideal destination for Japanese cuisine lovers looking to taste authentic flavors in Barcelona.',
    trick_es: 'No te pierdas el tempura de langostinos, es exquisito.',
    trick_en: "Don't miss the prawn tempura, it's exquisite.",
    schedules_es: 'Abierto de martes a domingo, de 6:00 p. m. a 11:00 p. m.',
    schedules_en: 'Open Tuesday to Sunday, from 6:00 p.m. to 11:00 p.m.',
    address: 'Carrer de Sardenya, 9, 08005 Barcelona, España',
    phones: '+34 932 21 76 19',
    booking_es: 'No es necesario reservar.',
    booking_en: 'No reservation required.',
    city: 'BCN',
    instagram: 'https://www.instagram.com/toukichirou/',
    avg_price: '20 euros - 30 euros',
    google_map_link: 'https://goo.gl/maps/7Z8ZQ5Q7ZQ7ZQ5Q7ZQ',
    official_url: 'https://www.toukichirou.com/',
    active: true,
    last_update: new Date(),
    created: new Date(),
  },
];

const food_burgers = [
  {
    category_id: 1,
    subcategory_id: 103,
    name: 'Asado Burgers',
    photos: [
      'https://thumbs2.imgbox.com/da/fd/bhznfnz0_t.jpeg',
      'https://thumbs2.imgbox.com/1b/41/r2QvJ31X_t.jpeg',
      'https://thumbs2.imgbox.com/30/ec/rm4ZMIZu_t.jpeg',
      'https://thumbs2.imgbox.com/db/92/YqcLtSwW_t.jpeg',
      'https://thumbs2.imgbox.com/69/c0/9D9BEZ29_t.jpeg',
    ],
    lat: 41.39320272732661,
    lng: 2.1495626511038535,
    description_es:
      'Asado Burgers es un lugar popular en Barcelona, España, conocido por sus deliciosas hamburguesas gourmet y su ambiente acogedor. Situado en el corazón del Barrio Gótico, este restaurante ofrece una amplia variedad de hamburguesas preparadas con ingredientes frescos y de alta calidad. Los clientes pueden disfrutar de una experiencia gastronómica única mientras saborean jugosas hamburguesas y acompañamientos caseros. Asado Burgers es el lugar perfecto para disfrutar de una comida reconfortante y satisfactoria en Barcelona.',
    description_en:
      'Asado Burgers is a popular spot in Barcelona, Spain, known for its delicious gourmet burgers and cozy atmosphere. Located in the heart of the Gothic Quarter, this restaurant offers a wide variety of burgers made with fresh, high-quality ingredients. Customers can enjoy a unique dining experience while savoring juicy burgers and homemade sides. Asado Burgers is the perfect place to enjoy a comforting and satisfying meal in Barcelona.',
    trick_es: 'No te pierdas su hamburguesa especial "Asado", es una delicia.',
    trick_en: 'Don\'t miss their special "Asado" burger, it\'s a delight.',
    schedules_es: 'Abierto todos los días de 12:00 p. m. a 11:00 p. m.',
    schedules_en: 'Open every day from 12:00 p.m. to 11:00 p.m.',
    address: 'Carrer dels Escudellers, 45, 08002 Barcelona, España',
    phones: '+34 933 02 06 82',
    booking_es: 'No es necesario reservar.',
    booking_en: 'No reservation required.',
    city: 'BCN',
    instagram: 'https://www.instagram.com/asadoburgers/',
    avg_price: '20 euros - 30 euros',
    google_map_link: 'https://goo.gl/maps/7Z8ZQ5Q7ZQ7ZQ5Q7ZQ',
    official_url: 'https://www.asadoburgers.com/',
    active: true,
    last_update: new Date(),
    created: new Date(),
  },
  {
    category_id: 1,
    subcategory_id: 103,
    name: 'La Royale',
    photos: [
      'https://thumbs2.imgbox.com/f3/dc/mGSXVPVt_t.jpeg',
      'https://thumbs2.imgbox.com/7d/78/nr2567wy_t.jpeg',
      'https://thumbs2.imgbox.com/f5/e6/NNLAbAbh_t.jpeg',
      'https://thumbs2.imgbox.com/26/71/bhfssxt9_t.jpeg',
      'https://thumbs2.imgbox.com/f6/88/48CIWORs_t.jpeg',
    ],
    lat: 41.40351443997406,
    lng: 2.1360867987114522,
    description_es:
      'La Royale es un restaurante de hamburguesas único en Barcelona, España, que combina sabores tradicionales con un toque contemporáneo. Ubicado en el corazón del Barrio Gótico, este restaurante ofrece una amplia selección de hamburguesas gourmet, desde clásicas hasta innovadoras. Los comensales pueden disfrutar de hamburguesas jugosas y acompañamientos caseros en un ambiente acogedor y relajado. La Royale es el destino perfecto para los amantes de las hamburguesas que buscan una experiencia gastronómica memorable en Barcelona.',
    description_en:
      'La Royale is a unique burger restaurant in Barcelona, Spain, that blends traditional flavors with a contemporary twist. Located in the heart of the Gothic Quarter, this restaurant offers a wide selection of gourmet burgers, from classic to innovative. Diners can enjoy juicy burgers and homemade sides in a cozy and relaxed atmosphere. La Royale is the perfect destination for burger lovers seeking a memorable dining experience in Barcelona.',
    trick_es: 'Prueba su hamburguesa "Royale Deluxe", una verdadera delicia.',
    trick_en: 'Try their "Royale Deluxe" burger, a true delight.',
    schedules_es:
      'Abierto de lunes a viernes de 1:00 p. m. a 11:00 p. m., sábados y domingos de 12:00 p. m. a 12:00 a. m.',
    schedules_en:
      'Open Monday to Friday from 1:00 p.m. to 11:00 p.m., Saturdays and Sundays from 12:00 p.m. to 12:00 a.m.',
    address: "Carrer de l'Allada-Vermell, 20, 08003 Barcelona, España",
    phones: '+34 932 68 39 38',
    booking_es: 'No es necesario reservar.',
    booking_en: 'No reservation required.',
    city: 'BCN',
    instagram: 'https://www.instagram.com/laroyalebcn/',
    avg_price: '20 euros - 30 euros',
    google_map_link: 'https://goo.gl/maps/7Z8ZQ5Q7ZQ7ZQ5Q7ZQ',
    official_url: 'https://www.laroyale.es/',
    active: true,
    last_update: new Date(),
    created: new Date(),
  },
];

const food_tacos = [
  {
    category_id: 1,
    subcategory_id: 104,
    name: 'Taco Alto',
    photos: [
      'https://thumbs2.imgbox.com/fc/f5/Fwg2c2GY_t.jpeg',
      'https://thumbs2.imgbox.com/75/2c/FsydJiEc_t.jpeg',
      'https://thumbs2.imgbox.com/03/d5/DSm2Lr1O_t.jpg',
      'https://thumbs2.imgbox.com/d2/32/pQr6cXtX_t.jpeg',
      'https://thumbs2.imgbox.com/56/c3/9Lz6Baqw_t.jpeg',
    ],
    lat: 41.37968606862493,
    lng: 2.167998515536272,
    description_es:
      'Taco Alto es un restaurante mexicano en Barcelona, España, que ofrece una auténtica experiencia gastronómica. Situado en el corazón del Barrio Gótico, este restaurante es conocido por sus deliciosos tacos y su ambiente animado. Los clientes pueden disfrutar de una amplia variedad de tacos, desde los clásicos hasta los más innovadores, preparados con ingredientes frescos y auténticos. Taco Alto es el destino perfecto para los amantes de la comida mexicana que buscan una experiencia auténtica en Barcelona.',
    description_en:
      'Taco Alto is a Mexican restaurant in Barcelona, Spain, that offers an authentic culinary experience. Located in the heart of the Gothic Quarter, this restaurant is known for its delicious tacos and lively atmosphere. Customers can enjoy a wide variety of tacos, from classic to innovative, prepared with fresh and authentic ingredients. Taco Alto is the perfect destination for Mexican food lovers looking for an authentic experience in Barcelona.',
    trick_es: 'No te pierdas sus tacos al pastor, son irresistibles.',
    trick_en: "Don't miss their al pastor tacos, they're irresistible.",
    schedules_es: 'Abierto todos los días de 1:00 p. m. a 12:00 a. m.',
    schedules_en: 'Open every day from 1:00 p.m. to 12:00 a.m.',
    address: 'Carrer dels Tallers, 73, 08001 Barcelona, España',
    phones: '+34 931 76 53 57',
    booking_es: 'No es necesario reservar.',
    booking_en: 'No reservation required.',
    city: 'BCN',
    instagram: 'https://www.instagram.com/tacoalto/',
    avg_price: '20 euros - 30 euros',
    google_map_link: 'https://goo.gl/maps/7Z8ZQ5Q7ZQ7ZQ5Q7ZQ',
    official_url: 'https://www.tacoalto.es/',
    active: true,
    last_update: new Date(),
    created: new Date(),
  },
  {
    category_id: 1,
    subcategory_id: 104,
    name: 'Tlaxcal',
    photos: [
      'https://thumbs2.imgbox.com/68/05/ISJD1tcz_t.jpeg',
      'https://thumbs2.imgbox.com/aa/36/NYPRZohL_t.jpeg',
      'https://thumbs2.imgbox.com/39/98/7Yw5qSRE_t.jpeg',
      'https://thumbs2.imgbox.com/5d/f7/MQYRGBCC_t.jpeg',
      'https://thumbs2.imgbox.com/f5/84/x5aMCZuB_t.jpeg',
    ],
    lat: 41.38515306464049,
    lng: 2.1842850391889073,
    description_es:
      'Tlaxcal es un restaurante mexicano único en Barcelona, España, que ofrece una auténtica experiencia culinaria. Ubicado en el corazón del Barrio Gótico, este restaurante sirve una amplia selección de platos mexicanos tradicionales, desde tacos hasta enchiladas. Los comensales pueden disfrutar de sabores auténticos mientras se sumergen en un ambiente acogedor y relajado. Tlaxcal es el destino ideal para aquellos que desean probar la verdadera cocina mexicana en Barcelona.',
    description_en:
      'Tlaxcal is a unique Mexican restaurant in Barcelona, Spain, offering an authentic culinary experience. Located in the heart of the Gothic Quarter, this restaurant serves a wide selection of traditional Mexican dishes, from tacos to enchiladas. Diners can enjoy authentic flavors while immersing themselves in a cozy and relaxed atmosphere. Tlaxcal is the ideal destination for those looking to taste real Mexican cuisine in Barcelona.',
    trick_es: 'Prueba sus enchiladas verdes, son una delicia.',
    trick_en: "Try their green enchiladas, they're delightful.",
    schedules_es:
      'Abierto de lunes a sábado de 1:00 p. m. a 11:00 p. m., domingos cerrado.',
    schedules_en:
      'Open Monday to Saturday from 1:00 p.m. to 11:00 p.m., closed on Sundays.',
    address: 'Carrer de Comte Borrell, 9, 08015 Barcelona, España',
    phones: '+34 934 24 61 43',
    booking_es: 'No es necesario reservar.',
    booking_en: 'No reservation required.',
    city: 'BCN',
    instagram: 'https://www.instagram.com/tlaxcalbcn/',
    avg_price: '20 euros - 30 euros',
    google_map_link: 'https://goo.gl/maps/7Z8ZQ5Q7ZQ7ZQ5Q7ZQ',
    official_url: 'https://www.tlaxcal.es/',
    active: true,
    last_update: new Date(),
    created: new Date(),
  },
];

const food_design = [
  {
    category_id: 1,
    subcategory_id: 105,
    name: 'Flax & Kale',
    photos: [
      'https://thumbs2.imgbox.com/a2/32/0grC9Lfj_t.jpeg',
      'https://thumbs2.imgbox.com/68/55/17Xo3fLd_t.png',
      'https://thumbs2.imgbox.com/d0/7a/nIKk9xMn_t.jpeg',
      'https://thumbs2.imgbox.com/6d/86/rmGXO5R8_t.jpeg',
      'https://thumbs2.imgbox.com/d1/6c/NFJDuA0R_t.png',
      'https://thumbs2.imgbox.com/b2/00/uw4jp2t2_t.jpeg',
    ],
    lat: 41.38564360403588,
    lng: 2.165466615016647,
    description_es:
      'Flax & Kale es un restaurante de diseño único en Barcelona, España, que combina comida saludable con un ambiente moderno. Situado en el corazón del Barrio Gótico, este restaurante ofrece una amplia variedad de platos vegetarianos y veganos, preparados con ingredientes frescos y de alta calidad. Los clientes pueden disfrutar de una experiencia gastronómica única mientras se relajan en un entorno elegante y contemporáneo. Flax & Kale es el lugar perfecto para aquellos que buscan una comida deliciosa y nutritiva en Barcelona.',
    description_en:
      'Flax & Kale is a unique design restaurant in Barcelona, Spain, that combines healthy food with a modern atmosphere. Located in the heart of the Gothic Quarter, this restaurant offers a wide variety of vegetarian and vegan dishes, prepared with fresh and high-quality ingredients. Customers can enjoy a unique gastronomic experience while relaxing in an elegant and contemporary environment. Flax & Kale is the perfect place for those looking for delicious and nutritious food in Barcelona.',
    trick_es: 'No te pierdas su jugo verde fresco, es refrescante y delicioso.',
    trick_en:
      "Don't miss their fresh green juice, it's refreshing and delicious.",
    schedules_es: 'Abierto todos los días de 9:00 a. m. a 11:00 p. m.',
    schedules_en: 'Open every day from 9:00 a.m. to 11:00 p.m.',
    address: 'Carrer dels Tallers, 74b, 08001 Barcelona, España',
    phones: '+34 933 17 56 64',
    booking_es: 'No es necesario reservar.',
    booking_en: 'No reservation required.',
    city: 'BCN',
    instagram: 'https://www.instagram.com/flaxandkale/',
    avg_price: '20 euros - 30 euros',
    google_map_link: 'https://goo.gl/maps/7Z8ZQ5Q7ZQ7ZQ5Q7ZQ',
    official_url: 'https://www.flaxandkale.com/',
    active: true,
    last_update: new Date(),
    created: new Date(),
  },
  {
    category_id: 1,
    subcategory_id: 105,
    name: 'Teresa Carles',
    photos: [
      'https://thumbs2.imgbox.com/c9/f2/4UUVg1fl_t.jpeg',
      'https://thumbs2.imgbox.com/9c/7b/ubzHIt0N_t.jpeg',
      'https://thumbs2.imgbox.com/c2/77/ES6dQhBf_t.jpeg',
      'https://thumbs2.imgbox.com/d1/a1/EHfrAODN_t.jpeg',
      'https://thumbs2.imgbox.com/4f/ee/pO7oqVsU_t.jpeg',
      'https://thumbs2.imgbox.com/3c/e2/trm4j59D_t.jpeg',
    ],
    lat: 41.38564181033072,
    lng: 2.1679385531887805,
    description_es:
      'Teresa Carles es un restaurante de diseño en Barcelona, España, que ofrece una experiencia culinaria innovadora. Ubicado en el corazón del Barrio Gótico, este restaurante se especializa en platos vegetarianos y veganos creativos, preparados con ingredientes frescos y locales. Los comensales pueden disfrutar de una amplia selección de opciones saludables mientras se sumergen en un ambiente moderno y acogedor. Teresa Carles es el destino ideal para aquellos que desean disfrutar de una comida deliciosa y nutritiva en Barcelona.',
    description_en:
      'Teresa Carles is a design restaurant in Barcelona, Spain, that offers an innovative culinary experience. Located in the heart of the Gothic Quarter, this restaurant specializes in creative vegetarian and vegan dishes, prepared with fresh and local ingredients. Diners can enjoy a wide selection of healthy options while immersing themselves in a modern and cozy atmosphere. Teresa Carles is the ideal destination for those looking to enjoy delicious and nutritious food in Barcelona.',
    trick_es:
      'No te pierdas su ensalada Teresa Carles, es una explosión de sabores.',
    trick_en: "Don't miss their Teresa Carles salad, it's a burst of flavors.",
    schedules_es: 'Abierto todos los días de 9:00 a. m. a 11:00 p. m.',
    schedules_en: 'Open every day from 9:00 a.m. to 11:00 p.m.',
    address: 'Carrer de Jovellanos, 2, 08001 Barcelona, España',
    phones: '+34 933 17 18 29',
    booking_es: 'No es necesario reservar.',
    booking_en: 'No reservation required.',
    city: 'BCN',
    instagram: 'https://www.instagram.com/teresacarles/',
    avg_price: '20 euros - 30 euros',
    google_map_link: 'https://goo.gl/maps/7Z8ZQ5Q7ZQ7ZQ5Q7ZQ',
    official_url: 'https://teresacarles.com/',
    active: true,
    last_update: new Date(),
    created: new Date(),
  },
];

const food_pizza = [
  {
    category_id: 1,
    subcategory_id: 106,
    name: 'NAP Molino',
    photos: [
      'https://thumbs2.imgbox.com/1e/16/YTkzOo7F_t.jpeg',
      'https://thumbs2.imgbox.com/6f/b3/4MbAdAeB_t.png',
      'https://thumbs2.imgbox.com/0d/09/0CZcUDar_t.png',
      'https://thumbs2.imgbox.com/0b/27/WckAm31I_t.jpeg',
      'https://thumbs2.imgbox.com/30/d8/YtpaAUAE_t.jpeg',
    ],
    lat: 41.37567340854918,
    lng: 2.1664389966622113,
    description_es:
      'NAP Molino es una pizzería popular en Barcelona, España, conocida por sus deliciosas pizzas y su ambiente acogedor. Situada en el corazón del Barrio Gótico, esta pizzería ofrece una amplia variedad de pizzas preparadas con ingredientes frescos y de alta calidad. Los clientes pueden disfrutar de una experiencia gastronómica única mientras saborean auténticas pizzas italianas en un ambiente relajado y acogedor. NAP Molino es el destino perfecto para los amantes de la pizza que buscan una experiencia memorable en Barcelona.',
    description_en:
      'NAP Molino is a popular pizzeria in Barcelona, Spain, known for its delicious pizzas and cozy atmosphere. Located in the heart of the Gothic Quarter, this pizzeria offers a wide variety of pizzas prepared with fresh and high-quality ingredients. Customers can enjoy a unique gastronomic experience while savoring authentic Italian pizzas in a relaxed and welcoming atmosphere. NAP Molino is the perfect destination for pizza lovers seeking a memorable experience in Barcelona.',
    trick_es:
      'No te pierdas su pizza Napoli, es una delicia auténtica italiana.',
    trick_en:
      "Don't miss their Napoli pizza, it's an authentic Italian delight.",
    schedules_es: 'Abierto todos los días de 12:00 p. m. a 12:00 a. m.',
    schedules_en: 'Open every day from 12:00 p.m. to 12:00 a.m.',
    address: 'Carrer de Sant Pau, 37, 08001 Barcelona, España',
    phones: '+34 933 10 07 14',
    booking_es: 'No es necesario reservar.',
    booking_en: 'No reservation required.',
    city: 'BCN',
    instagram: 'https://www.instagram.com/naprestaurants/',
    avg_price: '20 euros - 30 euros',
    google_map_link: 'https://goo.gl/maps/7Z8ZQ5Q7ZQ7ZQ5Q7ZQ',
    official_url: 'https://naprestaurants.com/molino/',
    active: true,
    last_update: new Date(),
    created: new Date(),
  },
  {
    category_id: 1,
    subcategory_id: 106,
    name: 'Nonno Zacca Pizzeria',
    photos: [
      'https://thumbs2.imgbox.com/11/49/Bbx8GyuH_t.png',
      'https://thumbs2.imgbox.com/26/10/krj5Ruhl_t.png',
      'https://thumbs2.imgbox.com/8e/5e/H0zGgl9E_t.jpeg',
      'https://thumbs2.imgbox.com/4a/19/da9m2u6P_t.jpeg',
      'https://thumbs2.imgbox.com/1f/25/LHrdMEBR_t.jpeg',
    ],
    lat: 41.38975681121429,
    lng: 2.146086934991146,
    description_es:
      'Nonno Zacca Pizzeria es una pizzería única en Barcelona, España, que ofrece una auténtica experiencia italiana. Ubicada en el corazón del Barrio Gótico, esta pizzería sirve una amplia selección de pizzas tradicionales, desde las clásicas margaritas hasta las innovadoras pizzas gourmet. Los comensales pueden disfrutar de sabores auténticos mientras se sumergen en un ambiente acogedor y relajado. Nonno Zacca Pizzeria es el destino ideal para aquellos que desean probar auténtica pizza italiana en Barcelona.',
    description_en:
      'Nonno Zacca Pizzeria is a unique pizzeria in Barcelona, Spain, that offers an authentic Italian experience. Located in the heart of the Gothic Quarter, this pizzeria serves a wide selection of traditional pizzas, from classic margheritas to innovative gourmet pizzas. Diners can enjoy authentic flavors while immersing themselves in a cozy and relaxed atmosphere. Nonno Zacca Pizzeria is the ideal destination for those looking to try authentic Italian pizza in Barcelona.',
    trick_es:
      'No te pierdas su pizza de trufa, es una experiencia culinaria única.',
    trick_en:
      "Don't miss their truffle pizza, it's a unique culinary experience.",
    schedules_es:
      'Abierto de domingo a jueves de 12:00 p. m. a 11:00 p. m., viernes y sábado de 12:00 p. m. a 12:00 a. m.',
    schedules_en:
      'Open Sunday to Thursday from 12:00 p.m. to 11:00 p.m., Friday and Saturday from 12:00 p.m. to 12:00 a.m.',
    address: 'Carrer dels Tallers, 74b, 08001 Barcelona, España',
    phones: '+34 933 17 56 64',
    booking_es: 'No es necesario reservar.',
    booking_en: 'No reservation required.',
    city: 'BCN',
    instagram: 'https://www.instagram.com/nonnozaccapizzeria/',
    avg_price: '20 euros - 30 euros',
    google_map_link: 'https://goo.gl/maps/7Z8ZQ5Q7ZQ7ZQ5Q7ZQ',
    official_url: 'https://www.nonnozaccapizzeria.com/',
    active: true,
    last_update: new Date(),
    created: new Date(),
  },
];

const food_panoramic = [
  {
    category_id: 1,
    subcategory_id: 107,
    name: 'El Xalet de Montjuïc',
    photos: [
      'https://thumbs2.imgbox.com/1e/16/YTkzOo7F_t.jpeg',
      'https://thumbs2.imgbox.com/6f/b3/4MbAdAeB_t.png',
      'https://thumbs2.imgbox.com/0d/09/0CZcUDar_t.png',
      'https://thumbs2.imgbox.com/0b/27/WckAm31I_t.jpeg',
      'https://thumbs2.imgbox.com/30/d8/YtpaAUAE_t.jpeg',
    ],
    lat: 41.369352306900325,
    lng: 2.164102895152244,
    description_es:
      'El Xalet de Montjuïc es un restaurante panorámico en Barcelona, España, que ofrece una experiencia culinaria única. Situado en la montaña de Montjuïc, este restaurante ofrece impresionantes vistas de la ciudad y el mar Mediterráneo. Los comensales pueden disfrutar de una amplia variedad de platos mediterráneos y catalanes, preparados con ingredientes frescos y de alta calidad. El Xalet de Montjuïc es el destino ideal para aquellos que buscan una experiencia gastronómica memorable en Barcelona.',
    description_en:
      'El Xalet de Montjuïc is a panoramic restaurant in Barcelona, Spain, offering a unique culinary experience. Located on the Montjuïc mountain, this restaurant offers stunning views of the city and the Mediterranean Sea. Diners can enjoy a wide variety of Mediterranean and Catalan dishes, prepared with fresh and high-quality ingredients. El Xalet de Montjuïc is the ideal destination for those looking for a memorable dining experience in Barcelona.',
    trick_es:
      'No te pierdas su arroz caldoso con bogavante, es una delicia mediterránea.',
    trick_en:
      "Don't miss their lobster rice stew, it's a Mediterranean delight.",
    schedules_es:
      'Abierto de lunes a domingo de 1:00 p. m. a 4:00 p. m., de 8:00 p. m. a 11:00 p. m.',
    schedules_en:
      'Open Monday to Sunday from 1:00 p.m. to 4:00 p.m., from 8:00 p.m. to 11:00 p.m.',
    address: 'Passeig de Montjuïc, 3, 08038 Barcelona, España',
    phones: '+34 934 30 03 00',
    booking_es: 'No es necesario reservar.',
    booking_en: 'No reservation required.',
    city: 'BCN',
    instagram: 'https://www.instagram.com/elxaletdemontjuic/',
    avg_price: '20 euros - 30 euros',
    google_map_link: 'https://goo.gl/maps/7Z8ZQ5Q7ZQ7ZQ5Q7ZQ',
    official_url: 'https://www.elxaletdemontjuic.com/',
    active: true,
    last_update: new Date(),
    created: new Date(),
  },
  {
    category_id: 1,
    subcategory_id: 107,
    name: "Torre d'alta mar",
    photos: [
      'https://thumbs2.imgbox.com/1e/16/YTkzOo7F_t.jpeg',
      'https://thumbs2.imgbox.com/6f/b3/4MbAdAeB_t.png',
      'https://thumbs2.imgbox.com/0d/09/0CZcUDar_t.png',
      'https://thumbs2.imgbox.com/0b/27/WckAm31I_t.jpeg',
      'https://thumbs2.imgbox.com/30/d8/YtpaAUAE_t.jpeg',
    ],
    lat: 41.373539137770834,
    lng: 2.187891132818972,
    description_es:
      "Torre d'alta mar es un restaurante panorámico en Barcelona, España, que ofrece una experiencia culinaria única. Situado en lo alto de una torre de cable en el puerto de Barcelona, este restaurante ofrece vistas impresionantes de la ciudad y el mar Mediterráneo. Los comensales pueden disfrutar de una amplia variedad de platos mediterráneos y catalanes, preparados con ingredientes frescos y de alta calidad. Torre d'alta mar es el destino ideal para aquellos que buscan una experiencia gastronómica memorable en Barcelona.",
    description_en:
      "Torre d'alta mar is a panoramic restaurant in Barcelona, Spain, offering a unique culinary experience. Located at the top of a cable car tower in the port of Barcelona, this restaurant offers stunning views of the city and the Mediterranean Sea. Diners can enjoy a wide variety of Mediterranean and Catalan dishes, prepared with fresh and high-quality ingredients. Torre d'alta mar is the ideal destination for those looking for a memorable dining experience in Barcelona.",
    trick_es:
      'No te pierdas su arroz caldoso con bogavante, es una delicia mediterránea.',
    trick_en:
      "Don't miss their lobster rice stew, it's a Mediterranean delight.",
    schedules_es:
      'Abierto de lunes a domingo de 1:00 p. m. a 4:00 p. m., de 8:00 p. m. a 11:00 p. m.',
    schedules_en:
      'Open Monday to Sunday from 1:00 p.m. to 4:00 p.m., from 8:00 p.m. to 11:00 p.m.',
    address: 'Passeig de Joan de Borbó, 88, 08039 Barcelona, España',
    phones: '+34 932 21 10 07',
    booking_es: 'No es necesario reservar.',
    booking_en: 'No reservation required.',
    city: 'BCN',
    instagram: 'https://www.instagram.com/torredealtamar/',
    avg_price: '20 euros - 30 euros',
    google_map_link: 'https://goo.gl/maps/7Z8ZQ5Q7ZQ7ZQ5Q7ZQ',
    official_url: 'https://www.torredealtamar.com/',
    active: true,
    last_update: new Date(),
    created: new Date(),
  },
];

const food_vegan = [
  {
    category_id: 1,
    subcategory_id: 108,
    name: 'Fat Veggies',
    photos: [
      'https://thumbs2.imgbox.com/1e/16/YTkzOo7F_t.jpeg',
      'https://thumbs2.imgbox.com/6f/b3/4MbAdAeB_t.png',
      'https://thumbs2.imgbox.com/0d/09/0CZcUDar_t.png',
      'https://thumbs2.imgbox.com/0b/27/WckAm31I_t.jpeg',
      'https://thumbs2.imgbox.com/30/d8/YtpaAUAE_t.jpeg',
    ],
    lat: 41.39641983837191,
    lng: 2.1714169588833094,
    description_es:
      'Fat Veggies es un restaurante vegano en Barcelona, España, que ofrece una experiencia culinaria saludable y deliciosa. Situado en el corazón de la ciudad, este restaurante sirve una amplia selección de platos veganos creativos y sabrosos. Los comensales pueden disfrutar de opciones saludables y nutritivas, preparadas con ingredientes frescos y de alta calidad. Fat Veggies es el destino ideal para aquellos que buscan una comida deliciosa y sana en Barcelona.',
    description_en:
      'Fat Veggies is a vegan restaurant in Barcelona, Spain, offering a healthy and delicious culinary experience. Located in the heart of the city, this restaurant serves a wide selection of creative and tasty vegan dishes. Diners can enjoy healthy and nutritious options, prepared with fresh and high-quality ingredients. Fat Veggies is the ideal destination for those looking for a delicious and healthy meal in Barcelona.',
    trick_es:
      'No te pierdas su hamburguesa vegana con queso de anacardos, es una delicia.',
    trick_en:
      "Don't miss their vegan burger with cashew cheese, it's a delight.",
    schedules_es: 'Abierto de lunes a domingo de 12:00 p. m. a 11:00 p. m.',
    schedules_en: 'Open Monday to Sunday from 12:00 p.m. to 11:00 p.m.',
    address: 'Carrer de la Fusina, 3, 08003 Barcelona, España',
    phones: '+34 932 68 39 38',
    booking_es: 'No es necesario reservar.',
    booking_en: 'No reservation required.',
    city: 'BCN',
    instagram: 'https://www.instagram.com/fatveggies/',
    avg_price: '20 euros - 30 euros',
    google_map_link: 'https://goo.gl/maps/7Z8ZQ5Q7ZQ7ZQ5Q7ZQ',
    official_url: 'https://www.fatveggies.com/',
    active: true,
    last_update: new Date(),
    created: new Date(),
  },
  {
    category_id: 1,
    subcategory_id: 108,
    name: 'Mundo Vegan',
    photos: [
      'https://thumbs2.imgbox.com/1e/16/YTkzOo7F_t.jpeg',
      'https://thumbs2.imgbox.com/6f/b3/4MbAdAeB_t.png',
      'https://thumbs2.imgbox.com/0d/09/0CZcUDar_t.png',
      'https://thumbs2.imgbox.com/0b/27/WckAm31I_t.jpeg',
      'https://thumbs2.imgbox.com/30/d8/YtpaAUAE_t.jpeg',
    ],
    lat: 41.389522161511685,
    lng: 2.157037835364915,
    description_es:
      'Mundo Vegan es un restaurante vegano en Barcelona, España, que ofrece una experiencia culinaria saludable y deliciosa. Situado en el corazón de la ciudad, este restaurante sirve una amplia selección de platos veganos creativos y sabrosos. Los comensales pueden disfrutar de opciones saludables y nutritivas, preparadas con ingredientes frescos y de alta calidad. Mundo Vegan es el destino ideal para aquellos que buscan una comida deliciosa y sana en Barcelona.',
    description_en:
      'Mundo Vegan is a vegan restaurant in Barcelona, Spain, offering a healthy and delicious culinary experience. Located in the heart of the city, this restaurant serves a wide selection of creative and tasty vegan dishes. Diners can enjoy healthy and nutritious options, prepared with fresh and high-quality ingredients. Mundo Vegan is the ideal destination for those looking for a delicious and healthy meal in Barcelona.',
    trick_es:
      'No te pierdas su hamburguesa vegana con queso de anacardos, es una delicia.',
    trick_en:
      "Don't miss their vegan burger with cashew cheese, it's a delight.",
    schedules_es: 'Abierto de lunes a domingo de 12:00 p. m. a 11:00 p. m.',
    schedules_en: 'Open Monday to Sunday from 12:00 p.m. to 11:00 p.m.',
    address: 'Carrer de la Fusina, 3, 08003 Barcelona, España',
    phones: '+34 932 68 39 38',
    booking_es: 'No es necesario reservar.',
    booking_en: 'No reservation required.',
    city: 'BCN',
    instagram: 'https://www.instagram.com/mundovegan/',
    avg_price: '20 euros - 30 euros',
    google_map_link: 'https://goo.gl/maps/7Z8ZQ5Q7ZQ7ZQ5Q7ZQ',
    official_url: 'https://www.mundovegan.com/',
    active: true,
    last_update: new Date(),
    created: new Date(),
  },
];

const food_sushi = [
  {
    category_id: 1,
    subcategory_id: 109,
    name: 'ELJ APO NÉS',
    photos: [
      'https://thumbs2.imgbox.com/1e/16/YTkzOo7F_t.jpeg',
      'https://thumbs2.imgbox.com/6f/b3/4MbAdAeB_t.png',
      'https://thumbs2.imgbox.com/0d/09/0CZcUDar_t.png',
      'https://thumbs2.imgbox.com/0b/27/WckAm31I_t.jpeg',
      'https://thumbs2.imgbox.com/30/d8/YtpaAUAE_t.jpeg',
    ],
    lat: 41.39526604022738,
    lng: 2.1605788436175652,
    description_es:
      'ELJ APO NÉS es un restaurante de sushi en Barcelona, España, que ofrece una experiencia culinaria auténtica. Situado en el corazón de la ciudad, este restaurante sirve una amplia selección de platos de sushi tradicionales y creativos. Los comensales pueden disfrutar de auténticos sabores japoneses mientras se sumergen en un ambiente acogedor y relajado. ELJ APO NÉS es el destino ideal para aquellos que buscan una experiencia gastronómica memorable en Barcelona.',
    description_en:
      'ELJ APO NÉS is a sushi restaurant in Barcelona, Spain, offering an authentic culinary experience. Located in the heart of the city, this restaurant serves a wide selection of traditional and creative sushi dishes. Diners can enjoy authentic Japanese flavors while immersing themselves in a cozy and relaxed atmosphere. ELJ APO NÉS is the ideal destination for those looking for a memorable dining experience in Barcelona.',
    trick_es:
      'No te pierdas su sushi de salmón, es fresco y delicioso. También ofrecen opciones veganas.',
    trick_en:
      "Don't miss their salmon sushi, it's fresh and delicious. They also offer vegan options.",
    schedules_es: 'Abierto de lunes a domingo de 12:00 p. m. a 11:00 p. m.',
    schedules_en: 'Open Monday to Sunday from 12:00 p.m. to 11:00 p.m.',
    address: 'Carrer de la Fusina, 3, 08003 Barcelona, España',
    phones: '+34 932 68 39 38',
    booking_es: 'No es necesario reservar.',
    booking_en: 'No reservation required.',
    city: 'BCN',
    instagram: 'https://www.instagram.com/eljapones/',
    avg_price: '20 euros - 30 euros',
    google_map_link: 'https://goo.gl/maps/7Z8ZQ5Q7ZQ7ZQ5Q7ZQ',
    official_url: 'https://www.eljapones.com/',
    active: true,
    last_update: new Date(),
    created: new Date(),
  },
  {
    category_id: 1,
    subcategory_id: 109,
    name: 'Hachiko',
    photos: [
      'https://thumbs2.imgbox.com/1e/16/YTkzOo7F_t.jpeg',
      'https://thumbs2.imgbox.com/6f/b3/4MbAdAeB_t.png',
      'https://thumbs2.imgbox.com/0d/09/0CZcUDar_t.png',
      'https://thumbs2.imgbox.com/0b/27/WckAm31I_t.jpeg',
      'https://thumbs2.imgbox.com/30/d8/YtpaAUAE_t.jpeg',
    ],
    lat: 41.375570203388776,
    lng: 2.1550476673764054,
    description_es:
      'Hachiko es un restaurante de sushi en Barcelona, España, que ofrece una experiencia culinaria auténtica. Situado en el corazón de la ciudad, este restaurante sirve una amplia selección de platos de sushi tradicionales y creativos. Los comensales pueden disfrutar de auténticos sabores japoneses mientras se sumergen en un ambiente acogedor y relajado. Hachiko es el destino ideal para aquellos que buscan una experiencia gastronómica memorable en Barcelona.',
    description_en:
      'Hachiko is a sushi restaurant in Barcelona, Spain, offering an authentic culinary experience. Located in the heart of the city, this restaurant serves a wide selection of traditional and creative sushi dishes. Diners can enjoy authentic Japanese flavors while immersing themselves in a cozy and relaxed atmosphere. Hachiko is the ideal destination for those looking for a memorable dining experience in Barcelona.',
    trick_es:
      'No te pierdas su sushi de salmón, es fresco y delicioso. También ofrecen opciones veganas.',
    trick_en:
      "Don't miss their salmon sushi, it's fresh and delicious. They also offer vegan options.",
    schedules_es: 'Abierto de lunes a domingo de 12:00 p. m. a 11:00 p. m.',
    schedules_en: 'Open Monday to Sunday from 12:00 p.m. to 11:00 p.m.',
    address: 'Carrer de la Fusina, 3, 08003 Barcelona, España',
    phones: '+34 932 68 39 38',
    booking_es: 'No es necesario reservar.',
    booking_en: 'No reservation required.',
    city: 'BCN',
    instagram: 'https://www.instagram.com/hachiko/',
    avg_price: '20 euros - 30 euros',
    google_map_link: 'https://goo.gl/maps/7Z8ZQ5Q7ZQ7ZQ5Q7ZQ',
    official_url: 'https://www.hachiko.com/',
    active: true,
    last_update: new Date(),
    created: new Date(),
  },
];

const food_seafood = [
  {
    category_id: 1,
    subcategory_id: 110,
    name: 'El Marisco',
    photos: [
      'https://thumbs2.imgbox.com/1e/16/YTkzOo7F_t.jpeg',
      'https://thumbs2.imgbox.com/6f/b3/4MbAdAeB_t.png',
      'https://thumbs2.imgbox.com/0d/09/0CZcUDar_t.png',
      'https://thumbs2.imgbox.com/0b/27/WckAm31I_t.jpeg',
      'https://thumbs2.imgbox.com/30/d8/YtpaAUAE_t.jpeg',
    ],
    lat: 41.373339660203534,
    lng: 2.165671156715421,
    description_es:
      'El Marisco es un restaurante de mariscos en Barcelona, España, que ofrece una experiencia culinaria fresca y deliciosa. Situado en el corazón de la ciudad, este restaurante sirve una amplia selección de platos de mariscos frescos y sabrosos. Los comensales pueden disfrutar de auténticos sabores del mar mientras se sumergen en un ambiente acogedor y relajado. El Marisco es el destino ideal para aquellos que buscan una experiencia gastronómica memorable en Barcelona.',
    description_en:
      'El Marisco is a seafood restaurant in Barcelona, Spain, offering a fresh and delicious culinary experience. Located in the heart of the city, this restaurant serves a wide selection of fresh and tasty seafood dishes. Diners can enjoy authentic sea flavors while immersing themselves in a cozy and relaxed atmosphere. El Marisco is the ideal destination for those looking for a memorable dining experience in Barcelona.',
    trick_es:
      'No te pierdas su paella de mariscos, es una delicia mediterránea.',
    trick_en: "Don't miss their seafood paella, it's a Mediterranean delight.",
    schedules_es: 'Abierto de lunes a domingo de 12:00 p. m. a 11:00 p. m.',
    schedules_en: 'Open Monday to Sunday from 12:00 p.m. to 11:00 p.m.',
    address: 'Carrer de la Fusina, 3, 08003 Barcelona, España',
    phones: '+34 932 68 39 38',
    booking_es: 'No es necesario reservar.',
    booking_en: 'No reservation required.',
    city: 'BCN',
    instagram: 'https://www.instagram.com/elmarisco/',
    avg_price: '20 euros - 30 euros',
    google_map_link: 'https://goo.gl/maps/7Z8ZQ5Q7ZQ7ZQ5Q7ZQ',
    official_url: 'https://www.elmarisco.com/',
    active: true,
    last_update: new Date(),
    created: new Date(),
  },
  {
    category_id: 1,
    subcategory_id: 110,
    name: "Peix d'Or. Restaurant",
    photos: [
      'https://thumbs2.imgbox.com/1e/16/YTkzOo7F_t.jpeg',
      'https://thumbs2.imgbox.com/6f/b3/4MbAdAeB_t.png',
      'https://thumbs2.imgbox.com/0d/09/0CZcUDar_t.png',
      'https://thumbs2.imgbox.com/0b/27/WckAm31I_t.jpeg',
      'https://thumbs2.imgbox.com/30/d8/YtpaAUAE_t.jpeg',
    ],
    lat: 41.39493216821234,
    lng: 2.1788343254066023,
    description_es:
      "Peix d'Or. Restaurant es un restaurante de mariscos en Barcelona, España, que ofrece una experiencia culinaria fresca y deliciosa. Situado en el corazón de la ciudad, este restaurante sirve una amplia selección de platos de mariscos frescos y sabrosos. Los comensales pueden disfrutar de auténticos sabores del mar mientras se sumergen en un ambiente acogedor y relajado. Peix d'Or. Restaurant es el destino ideal para aquellos que buscan una experiencia gastronómica memorable en Barcelona.",
    description_en:
      "Peix d'Or. Restaurant is a seafood restaurant in Barcelona, Spain, offering a fresh and delicious culinary experience. Located in the heart of the city, this restaurant serves a wide selection of fresh and tasty seafood dishes. Diners can enjoy authentic sea flavors while immersing themselves in a cozy and relaxed atmosphere. Peix d'Or. Restaurant is the ideal destination for those looking for a memorable dining experience in Barcelona.",
    trick_es:
      'No te pierdas su paella de mariscos, es una delicia mediterránea.',
    trick_en: "Don't miss their seafood paella, it's a Mediterranean delight.",
    schedules_es: 'Abierto de lunes a domingo de 12:00 p. m. a 11:00 p. m.',
    schedules_en: 'Open Monday to Sunday from 12:00 p.m. to 11:00 p.m.',
    address: 'Carrer de la Fusina, 3, 08003 Barcelona, España',
    phones: '+34 932 68 39 38',
    booking_es: 'No es necesario reservar.',
    booking_en: 'No reservation required.',
    city: 'BCN',
    instagram: 'https://www.instagram.com/peixdor/',
    avg_price: '20 euros - 30 euros',
    google_map_link: 'https://goo.gl/maps/7Z8ZQ5Q7ZQ7ZQ5Q7ZQ',
    official_url: 'https://www.peixdor.com/',
    active: true,
    last_update: new Date(),
    created: new Date(),
  },
];

const food_subcategories = [
  {
    id: '100',
    name: 'Tapas',
    category_id: '1',
    t_name: 'subcat_tapas',
    icon: 'tapas.svg',
  },
  {
    id: '102',
    category_id: '1',
    name: 'Catalan',
    t_name: 'subcat_catalan',
    icon: 'catalan.svg',
  },
  {
    id: '103',
    name: 'Burgers',
    category_id: '1',
    t_name: 'subcat_burgers',
    icon: 'burgers.svg',
  },
  {
    id: '104',
    name: 'Tacos',
    category_id: '1',
    t_name: 'subcat_tacos',
    icon: 'tacos.svg',
  },
  {
    id: '105',
    name: 'Design',
    category_id: '1',
    t_name: 'subcat_design',
    icon: 'design.svg',
  },
  {
    id: '106',
    name: 'Pizza',
    category_id: '1',
    t_name: 'subcat_pizza',
    icon: 'pizza.svg',
  },
  {
    id: '107',
    name: 'Panoramic',
    category_id: '1',
    t_name: 'subcat_panoramic',
    icon: 'panoramic.svg',
  },
  {
    id: '108',
    name: 'Vegan',
    category_id: '1',
    t_name: 'subcat_vegan',
    icon: 'vegan.svg',
  },
  {
    id: '109',
    name: 'Sushi',
    category_id: '1',
    t_name: 'subcat_sushi',
    icon: 'sushi.svg',
  },
  {
    id: '110',
    name: 'Seafood',
    category_id: '1',
    t_name: 'subcat_seafood',
    icon: 'seafood.svg',
  },
];

const food_places = [
  ...food_tapas,
  ...food_catalan,
  ...food_burgers,
  ...food_tacos,
  ...food_design,
  ...food_pizza,
  ...food_panoramic,
  ...food_vegan,
  ...food_sushi,
  ...food_seafood,
];

module.exports = { food_places, food_subcategories };
